version: '2'

services:
  sh:
    build:
      context: .docker/php@7.2/cli
    user: docker:docker
    volumes:
      - ./:/var/www/html
      - $HOME/.ssh:/opt/docker/:cached
    restart: "always"
    command: [ "sleep", "31536000" ]

  sh-xdebug:
    build:
      context: .docker/php@7.2/cli-xdebug
    user: docker:docker
    volumes:
      - $HOME/.ssh:/opt/docker/:cached
      - ./:/var/www/html
    restart: "always"
    command: [ "sleep", "31536000" ]

volumes:
  composer:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "size=2048m,uid=1000,gid=1000"